// Map complains to mp3.

module.exports = {
  "Animal Abuse": 0,
  "Building/Use": 1,
  "Elevator": 2,
  "Blocked Driveway": 3,
  "Noise - Street/Sidewalk": 3,
  "Illegal Parking": 3,
  "Dirty Conditions": 4,
  "Sanitation Condition": 4,
  "Noise - Residential": 5,
  "Noise - Park": 6,
  "Non-Emergency Police Matter":7,
  "Derelict Vehicles": 8,
  "Street Condition": 8,
  "Maintenance or Facility": 9,
  "General Construction/Plumbing": 9,
  "Rodent":10,
  "Noise - Vehicle": 11,
  "Street Light Condition": 11,
  "Noise": 11,
  "Noise - Commercial": 12,
  "Traffic Signal Condition": 13,
  "Sewer": 14,
  "Water System": 15,
  "HEAT/HOT WATER": 16,
  "Missed Collection (All Materials)": 17,
  "Overflowing Litter Baskets": 18,
  "Illegal Fireworks": 19,
  "Plant": 20,
  "Illegal Tree Damage": 21,
  "New Tree Request": 22,
  "Overgrown Tree/Branches": 23
}